### ISSUE TITLE
Ошибка при добавлении новой метрики в Тик Токе

### ISSUE THREAD

**Issue by sergneverov** [NPodlozhniy/marketing-pipeline#1]
Привет, спасибо за код, особенно за часть с тик током. Но когда я пытаюсь в этот код добавить новую метрику, связанную с урлом "landing_page_url" то мне выскакивает ошибка

AttributeError: 'DataFrame' object has no attribute 'spend'

Причём с другими метриками таких проблем нет.

**Comment by NPodlozhniy** [comment]
Привет, очень рад обратной связи! Сейчас немного забросил поддержку актуальности этого репозитория, но!

Первая догадка следующая: возможно дело не в новой добавленной метрике, а в том, что ты убрал из списка METRICS метрику `spend`. Код при этом скорее всего валится на строчке `df["spend"] = df.spend.apply(float)`

Если это не поможет - скидывай более подробно ошибку, попробуй выполнять код по строчкам чтобы понять, где именно он падает, я смогу посмотреть и ответить на выходных!

**Comment by sergneverov** [comment]
Да эту строчку я не трогал, но кажется понял в чём проблема - у тик тока же несколько типов отчётов и уровней данных, и вот в твоём примере как раз тот уровень, у которого просто нет урла как метрики. Вот видимо он и ругается что нет костов, попробую с разными типами отчёта поэкспериментировать.

**Comment by NPodlozhniy** [comment]
Да, возможно ты прав, это была моя следующая гипотеза. Смотри там внимательно документацию, при каких типах отчетов, что можно получать. Сообщи о прогрессе!

**Comment by sergneverov** [comment]
Да действительно, в BASIC репорте можно только имена кампаний и групп выгружать
https://ads.tiktok.com/marketing_api/docs?id=1707957200780290

Если нужна инфа по урлам, надо идти тогда в Playable ad report, но в нём нет названий кампаний и груп, а они мне тоже нужны. Странное у них апи в общем, но что-то придумаю)
https://ads.tiktok.com/marketing_api/docs?id=1707958874953730

 Спасибо еще раз за скрипт, оч выручил с ним.
